version: '3'
services:
  mydb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
    ports:
      - 3306:3306
    volumes:
      - ~/desktop/workspace/my.cnf:/etc/mysql/conf.d/my.cnf
      - ~/desktop/workspace:/var/lib/mysql
